### ISSUE TITLE
shmem_put_signal() generic selection failing on example code

### ISSUE THREAD

**Issue by brianlarkins** [Sandia-OpenSHMEM/SOS#1006] opened 2021-07-16 18:56 UTC
i'm getting C11 selection errors when trying to compile Example 27 from the 1.5 spec, which uses shmem_put_signal().

configure:   $ ./configure --prefix=/opt/tools/modules/sandia-openshmem --without-ofi --with-ucx --with-pmi=/opt/scyld/slurm

When compiling the example code I get the following error:
```
/opt/tools/modules/sandia-openshmem/include/shmem.h:5819:13: error: expected ')' before 'default'
 5819 |             default: shmem_ctx_c11_generic_selection_failed \
      |             ^~~~~~~
signal_test.c:24:5: note: in expansion of macro 'shmem_put_signal'
   24 |     shmem_put_signal(data, message, size, &sig_addr, 1, SHMEM_SIGNAL_SET, pe);
```

This happens when compiling SOS with gcc-10.2.0. Similar results with Clang 11.0 and AOCC (Clang 12.0).
example code attached.

brian.

[signal_test.txt](https://github.com/Sandia-OpenSHMEM/SOS/files/6832808/signal_test.txt)

**Comment by davidozog** [comment] 2021-07-16 21:20
Thanks for the bug report @brianlarkins - I can reproduce the error.

We intended to include all the spec examples in the SOS unit tests, but somehow this one is missing.  Let's not close this issue until this program is added to `test/spec-examples`.

Looks like the issue is just a missing comma.  @brianlarkins - you please check whether PR #1007 fixes the problem.  You can also add the missing comma right after `shmem_ctx_ulonglong_put_signal` in the installed header file (line 5818) if that's easier...

Also it looks looks like this issue is related to #933.  `put` and `get` do not use `shmem_ctx_c11_generic_selection_failed`, but `put_signal` does...

**Comment by brianlarkins** [comment] 2021-07-16 22:36
@davidozog i checked out the PR and it looks like that fixed the problem.

thanks for the quick turnaround.

b.

**Closed** 2021-08-11 18:33 UTC
