### ISSUE TITLE
GUPS bug

### ISSUE THREAD

**Issue by kseager** [Sandia-OpenSHMEM/SOS#348] opened 2017-03-07 16:41 UTC
improved error checking has revealed the following error in the gups app:

ERROR: shmem_int_sum_to_all(): Argument "pSync" [0x6022e0..0x6023f8) exceeds sym. data region [0x6020d8..0x602330)
ERROR: shmem_int_sum_to_all(): Argument "pSync" [0x6022e0..0x6023f8) exceeds sym. data region [0x6020d8..0x602330)

additionally add apps tests to travis

**Comment by davidozog** [comment] 2017-03-08 15:49
I'm pretty sure the problem is simply the use of SHMEM_BCAST_SYNC_SIZE when SHMEM_REDUCE_SYNC_SIZE is the correct choice, so I'll just make the change.  However, I can't reproduce the bug locally, so I'm curious - which system do you see this error?

And just to clarify, we want gups in the default tests as well, not just with --enable-lengthy-tests?  It looks like binary-search is in currently in default and gups in lengthy.

**Comment by jdinan** [comment] 2017-03-08 16:37
The discrepancy you found sounds like the source of the error.

It's unfortunately pretty random when the error checking catches these errors.  It depends on the layout of the data segment and whether the pSync crosses over the end of it.  You could try using a different compiler.  Otherwise, the best thing to do would be for @kseager to try out your patch on the machine where she saw the error.

**Comment by jdinan** [comment] 2017-03-08 19:03
Fixed by #350

**Closed by jdinan** 2017-03-08 19:03 UTC
Labels: bug
