### ISSUE TITLE
Wrong signature for shmem_team_get_config

### ISSUE THREAD

**Issue by dalcinl** [Sandia-OpenSHMEM/SOS#1016] opened 2021-09-29 14:28 UTC
Currently, `shmem.h` contains the following declaration:
```c
void shmem_team_get_config(shmem_team_t team, shmem_team_config_t *config);
```

However, this is not the proper function signature corresponding to OpenSHMEM v1.5, it should be:
```c
int shmem_team_get_config(shmem_team_t team, long config_mask, shmem_team_config_t *config);
```
that is, the `long config_mask` argument is missing, the it should return `int`.

**Comment by dalcinl** [comment] 2021-09-29 14:29
@davidozog Here you have another one to keep you busy. I hope this one is easy.

**Comment by davidozog** [comment] 2021-09-29 14:39
Thanks @dalcinl - I think this is a duplicate of #992, and yes - it should be an easy fix.  `shmem_team_get_config` should return an `int` right?

**Comment by dalcinl** [comment] 2021-09-29 15:13
> I think this is a duplicate of #992

Yes, indeed. Sorry!

> should return an int right?

O yes, sorry again. I edited the description. 

I guess you can close this one as a duplicate.

**Comment by davidozog** [comment] 2021-09-29 15:22
No problem - closing as a duplicate.

**Closed by davidozog** 2021-09-29 15:22 UTC
Labels: duplicate
