### ISSUE TITLE
Perf suite bandwidth too high

### ISSUE THREAD

**Issue by davidozog** [Sandia-OpenSHMEM/SOS#665] opened 2018-04-04 18:44 UTC

**Comment by davidozog** [comment] 2018-04-17 21:37
Hi @wrrobin.  On Cori@NERSC, I see the following:
```
Incorrect time measured from bandwidth test: start_min = 0.000000, end_max = 0.000000
```

Is that because `perf_shmemx_wtime()` has an issue on Cori?  The bandwidth numbers look fine...

Here's how I'm running (2 nodes, 1 PE per node):
srun -N 2 -n 2 -C haswell ./test/performance/shmem_perf_suite/shmem_bw_put_perf

**Comment by wrrobin** [comment] 2018-04-17 22:16
Thanks @davidozog. I will test it out myself to see what the issue is. But, if you have the entire output handy, can you please paste it here?

**Comment by wrrobin** [comment] 2018-04-18 03:03
Yes, the issue is related to multiple HFI. We can also add the environment variable, `HFI_UNIT` to Wiki. This is read by the PSM provider and can be used to select a single HFI in such instance. 

Since the issue is resolved now, I am closing it.

**Closed by wrrobin** 2018-04-18 03:03 UTC
